var helpPage = [] ;

function choiLang(i) {
	document.getElementById('avertissement').innerHTML = helpPage[i] ;	
}

helpPage[0]  = '<center> <img alt="flag" src="images/fr-us-uk-flag.png" onclick="choiLang(1)"/><br><p style="font-size:28px">L\'Arithmaurel fut acclamé en son temps comme une machine révolutionnaire.</p>'
+ '<a href="http://www.aconit.org/" target="_blank"><img id="logoAconit" src="images/logo.jpg" alt="Logo ACONIT"/></a></center><br>'
+ 'En effet, cette « <b>horloge à calcul</b> » effectuait les quatre opérations arithmétiques sans manivelle ni moteur, sans qu’il soit nécessaire de connaître les algorithmes de ces opérations'
+ ' et d’apprendre les tables de Pythagore. Il suffisait de poser les opérandes, et c’était fait. Une telle prouesse ne s’était jamais vue et ne se reverra que plus de 60 ans plus tard avec'
+ ' des machines mécaniques munies d’un moteur électrique. <br>'
+ 'Dans l’arithmaurel de 1850 le premier opérande (le multiplicande) se pose avec les 8 tirettes en haut de la machine. Sa valeur initiale est 1. Cliquer une des 8 tirettes du dessin ci-contre (bouton en laiton)'
+ ' et tirez la vers le bas pour augmenter la valeur d’un chiffre de l’opérande, ou vers le haut pour la diminuer. <table><td>Dans l’arithmaurel réel, les chiffres des tirettes apparaissent au-dessus de chaque tirette.<br>'
+ ' Par exemple les tirettes  de la figure à droite affichent le nombre 0 0 0 0 0 1 2 4.<br> Dans le simulateur ci-contre les valeurs des tirettes sont affichées au-dessus de la machine.'
+ '</td><td><center><img alt="tirettes" src="images/tirettes.jpg"/></center></td></table>'
+ 'Remettez à 1 la valeur du multiplicande (ou rechargez simplement la page), puis faites tourner les aiguilles. <br> Cliquez sur une aiguille dans l’un des 4 cadrans blancs (des cadrans émaillés de montre)'
+ ' et déplacez la pointe de l’aiguille. Notez que dans l’arithmaurel réel, on la tournait avec un gros écrou à oreilles situé sous le cadran. Une démultiplication permettait de positionner sans forcer l’aiguille'
+ ' avec précision. Vous pouvez obtenir un effet similaire en cliquant une aiguille puis en déplaçant le pointeur bien à l’extérieur du cadran pour allonger le bras de levier. <br>'
+ 'Un dispositif astucieux permettait d’obtenir mécaniquement un effet d’arrondi à l’entier le plus proche du cadran. <br>'
+ 'Un mécanisme emprunté aux chronomètres remet les aiguilles à 0 pratiquement instantanément (touche <font face=Arial><small><i>Effacer les cadrans</i></small></font>). <br>' 
+ 'Observez que lorsqu’on tourne une aiguille vers la droite (sens des aiguilles d’une montre) l’arithmaurel effectue une soustraction, et une addition pour le sens opposé. <br>'
+ ' Pour effectuer une suite d’additions/soustractions de nombres on laisse le multiplicande à 1 puis on itère effacement des cadrans et pose d’un nombre en tournant les aiguilles.'
+ ' Bien entendu les aiguilles sont tournées à gauche pour les additions, et à droite pour les soustractions. <br> La multiplication est effectuée en posant le multiplicande avec les 8 tirettes du haut,'
+ ' puis le multiplieur avec les aiguilles. Si on a préalablement effacé le totalisateur, on a une multiplication, dans le cas contraire une somme de produits. Remarquons qu’une somme est finalement une somme'
+ ' de produits par 1. <br> Pour une division on amène le dividende dans le totalisateur, ce sera le reste initial, puis le diviseur dans les tirettes, et enfin on tourne les aiguilles, en partant de la gauche,'
+ ' afin de minimiser le reste tout en le gardant positif ou nul. <br>'
+ 'Avant l’opération n’oubliez pas de mémoriser la valeur du dividende, qui sera perdue. En effet une division utilise 4 variables (dividende, diviseur, quotient et reste), et la machine peut n’en afficher que 3.<br>'
+ '<a href="https://www.aconit.org/histoire/calcul_mecanique/documents/arithmaurel.pdf" target="_blank">En savoir plus sur l\'Arithmaurel ?</a>.<br>'
+ 'Vous pouvez aussi laisser l’ordinateur faire travailler l’Arithmaurel et regarder en cliquant <b>&nbsp;+&nbsp;&nbsp;&nbsp;−&nbsp;&nbsp;&nbsp;×&nbsp;&nbsp;&nbsp;÷&nbsp;&nbsp;&nbsp;Σ</b>. Le petit curseur règle la vitesse.'

helpPage[1]  = '<center> <img alt="flag" src="images/fr-us-uk-flag.png" onclick="choiLang(0)"/><br><p style="font-size:28px">The Arithmaurel was acclaimed in its time as a revolutionary machine.</p>'
+ '<a href="http://www.aconit.org/" target="_blank"><img id="logoAconit" src="images/logo.jpg" alt="Logo ACONIT"/></a></center><br>'
+ 'Indeed, this "<b>calculating clock</b>", with neither a crank handle nor a motor, was able to carry out the four arithmetic operations, without having to understand the algorithms of these operations, or learn the Pythagorean tables.'
+ ' All that was required was to set the operands, and that was it. Such prowess had never been seen before, and would not be seen again until 60 years later, with the arrival of mechanical machines equipped with an electric motor.<br>'
+ ' For the 1850 Arithmaurel, the first operand (the multiplicand) is set using the 8 knobs at the top of the machine. It\'s initial value is 1. Click on one of the 8 knobs on the illustration opposite (brass button)'
+ ' and pull it downwards to increase the value of a digit of the operand, or upwards to decrease it. <table><td>In the actual Arithmaurel, the value of each digit of the operand is displayed above the corresponding sliding knob.<br>'
+ ' As an example, the knobs of the figure at right display the number 0 0 0 0 0 1 2 4.<br>In the illustration opposite they are displayed above the machine image in the central display.<br>'
+ '</td><td><center><img alt="tirettes" src="images/tirettes.jpg"/></center></td></table>'
+ ' Re-set the value of the multiplicand to 1 (or re-load the page), then turn the pointers of the dials. Click on the pointer of one of the 4 white dials (the enameled clock faces) and move the end of the pointer.'
+ ' Note that for the real Arithmaurel, one turned the hands using a large wing nut situated below the dial. A gearing down allowed one to position the pointer precisely, without forcing it. You can obtain a similar effect'
+ ' by clicking on a dial hand and then moving the mouse pointer well outside the dial, to extend the lever arm.<br>'
+ ' An ingenious device is used to obtain mechanically a rounding effect to the nearest digit of a dial. A mechanism borrowed from chronometers re-sets the pointers to zero almost instantaneously'
+ ' (button <font face=Arial><small><i>Effacer les cadrans</i></small></font>). <br>'
+ ' Note that when one turns a pointer towards the right (clockwise) the Arithmaurel carries out a subtraction, and an addition for the opposite sense.<br> A series of additions/subtractions may be carried out by leaving'
+ ' the multiplicand set to 1 and then successively iterating clearing the dials and setting a number by turning the pointers. Of course, the pointers are turned in the clockwise direction for subtraction, and anti-clockwise'
+ ' for addition.<br>'
+ ' Multiplication is carried out by setting the multiplicand using the 8 knobs at the top, followed by setting the multiplier using the dials. If the accumulator had been previously set to zero '
+ '(using the button <font face=Arial><small><i>Effacer le totalisateur</i></small></font>) one obtains a multiplication; otherwise one obtains a sum of products (the pointers must be set to zero between each operation,'
+ ' using the button <font face=Arial><small><i>Effacer les cadrans</i></small></font>). Note that one can consider a sum of numbers as a sum of products with a multiplicand of 1.<br>'
+ ' For a division, one first sets the dividend using the knobs and rotating the right hand dial anti-clockwise to 1. One then clears the dials (button <font face=Arial><small><i>Effacer les cadrans</i></small></font>) and sets the divisor using the knobs.'
+ ' The division is then performed by progressively turning the dial pointers clockwise, starting from the right-hand dial, such as to minimise the remainder (accumulator), while keeping it positive or null.'
+ ' The result is given by the positions of the dial pointers, with the remainder in the accumulator. Before carrying out the division one should note the value of the dividend, which will be lost in the operation.'
+ ' The reason is that division involves 4 variables (dividend, divisor, quotient and remainder) and the machine can only display 3.<br>'
+ '<a href="https://www.aconit.org/histoire/calcul_mecanique/documents/arithmaurel.pdf" target="_blank">Learn more about the Arithmaurel? (In French)</a>.<br>'
+ ' You may also let your computer run calculations on the Arithmaurel by clicking on <b>&nbsp;+&nbsp;&nbsp;&nbsp;−&nbsp;&nbsp;&nbsp;×&nbsp;&nbsp;&nbsp;÷&nbsp;&nbsp;&nbsp;Σ</b>. The small cursor adjusts the speed of simulation.'

